#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XamSvgTests.Resource", IsApplication=true)]

namespace XamSvgTests
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::XamSvg.Resource.String.library_name = global::XamSvgTests.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000e
			public const int bitmap1 = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int bitmap2 = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int bitmap3 = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int drawable100 = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int drawable16 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int drawable24 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int drawable32 = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int drawable50 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int drawable71 = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int drawableHeight = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int drawableWidth = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout2 = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout3 = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout4 = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int textView1 = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int textView2 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int bike = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int bike_separator = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ic_lock = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int map = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int pin = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int star_depressed = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int star_off = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int star_on = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int tiger = 2130968584;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
